### ISSUE TITLE
Even after logging out, TA will remained checked-in for office hours. 

### ISSUE THREAD

**Issue by aknbaig** [bekher/officehours#27]
Possibly having a timer to kick TA after a certain time or just kicking TA from being active when they are not logged in.

**Comment by dkaps125** [comment]
The above commit should fix this issue...Just need @bekher to take a look and merge.

**Comment by bekher** [comment]
Merge looks good, I'll hot patch this in now. There is already a timer to log TA's out of OH if they've been logged in for >=2 hours.
